
;  This file was generated by the SOM Compiler.
;  FileName: .\WPDCF77.def.
;  Generated using:
;      SOM Precompiler spc: 1.22
;      SOM Emitter emitdef: 1.13
;  Description modified 06-15-1995
LIBRARY WPDCF77 INITINSTANCE

PROTMODE

DESCRIPTION '@#NB:X.XX.XX#@ WPDCF77 Class Library'

DATA MULTIPLE NONSHARED READWRITE LOADONCALL

CODE LOADONCALL

EXPORTS
   WPDCF77CClassData
   WPDCF77ClassData
   WPDCF77NewClass
   M_WPDCF77CClassData
   M_WPDCF77ClassData
   M_WPDCF77NewClass
