
/*
 * This file was generated by the SOM Compiler.
 * FileName: .\wpdcf77.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * 
 *    Module Name: wpDCF77
 * 
 *    OS/2 Workplace Shell clock w/ DCF77 support
 * 
 */


#ifndef SOM_WPDCF77_h
#define SOM_WPDCF77_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPDCF77
#define WPDCF77 SOMObject
#endif
/*
 * Symbol parentComment is undefined
 * 
 *  CLASS: WPClock
 * 
 *  CLASS HIERARCHY:
 * 
 *      SOMObject
 *        ¿ƒƒ WPObject
 *              ¿ƒƒ WPAbstract
 *                    ¿ƒƒ WPClock
 *                          ¿ƒƒ WPDCF77
 * 
 */
#include <wpclock.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPAbstract
    #define M_WPAbstract SOMObject
#endif /* M_WPAbstract */
#ifndef M_WPClock
    #define M_WPClock SOMObject
#endif /* M_WPClock */
#ifndef M_WPDCF77
    #define M_WPDCF77 SOMObject
#endif /* M_WPDCF77 */
#define WPDCF77_CCHMAXPGNAME 32 /* 32 */
/*
 *  max. StringlÑnge fÅr Seitennamen und andere Stringresourcen
 */

#define WPDCF77_CCHMAXALARMMSG 128 /* 128 */
/*
 *  max. StringlÑnge fÅr den Alarmtext
 */

#define WPDCF77_CCHMAXTZONE 25 /* 25 */
/*
 *  max. StringlÑnge fÅr Zeitzone
 */

#define WPDCF77_CCHMAXDATETIME 12 /* 12 */
/*
 *  max. StringlÑnge fÅr Zeit-/Datumstring
 */

#define WPDCF77_CCHMAXPARM 256 /* 256 */
/*
 *  max. StringlÑnge fÅr Parameterstring Alarmprogramm
 */

#define WPDCF77_MINMAX_NORMAL 0 /* 0 */
/*
 *  Min/Max: Normalzustand"
 */

#define WPDCF77_MINMAX_CHANGED 1 /* 1 */
/*
 *  Min/Max: WM_MINMAXFRAME empfangen"
 */

#define WPDCF77_MINMAX_WAIT4SIZE 2 /* 2 */
/*
 *  Min/Max: Warten auf WM_SIZE"
 */


#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_CCHMAXPGNAME
    #ifdef CCHMAXPGNAME
        #undef CCHMAXPGNAME
        #define SOMTGD_CCHMAXPGNAME 1
    #else
        #define CCHMAXPGNAME WPDCF77_CCHMAXPGNAME
    #endif /* CCHMAXPGNAME */
#endif /* SOMTGD_CCHMAXPGNAME */
#ifndef SOMTGD_CCHMAXALARMMSG
    #ifdef CCHMAXALARMMSG
        #undef CCHMAXALARMMSG
        #define SOMTGD_CCHMAXALARMMSG 1
    #else
        #define CCHMAXALARMMSG WPDCF77_CCHMAXALARMMSG
    #endif /* CCHMAXALARMMSG */
#endif /* SOMTGD_CCHMAXALARMMSG */
#ifndef SOMTGD_CCHMAXTZONE
    #ifdef CCHMAXTZONE
        #undef CCHMAXTZONE
        #define SOMTGD_CCHMAXTZONE 1
    #else
        #define CCHMAXTZONE WPDCF77_CCHMAXTZONE
    #endif /* CCHMAXTZONE */
#endif /* SOMTGD_CCHMAXTZONE */
#ifndef SOMTGD_CCHMAXDATETIME
    #ifdef CCHMAXDATETIME
        #undef CCHMAXDATETIME
        #define SOMTGD_CCHMAXDATETIME 1
    #else
        #define CCHMAXDATETIME WPDCF77_CCHMAXDATETIME
    #endif /* CCHMAXDATETIME */
#endif /* SOMTGD_CCHMAXDATETIME */
#ifndef SOMTGD_CCHMAXPARM
    #ifdef CCHMAXPARM
        #undef CCHMAXPARM
        #define SOMTGD_CCHMAXPARM 1
    #else
        #define CCHMAXPARM WPDCF77_CCHMAXPARM
    #endif /* CCHMAXPARM */
#endif /* SOMTGD_CCHMAXPARM */
#ifndef SOMTGD_MINMAX_NORMAL
    #ifdef MINMAX_NORMAL
        #undef MINMAX_NORMAL
        #define SOMTGD_MINMAX_NORMAL 1
    #else
        #define MINMAX_NORMAL WPDCF77_MINMAX_NORMAL
    #endif /* MINMAX_NORMAL */
#endif /* SOMTGD_MINMAX_NORMAL */
#ifndef SOMTGD_MINMAX_CHANGED
    #ifdef MINMAX_CHANGED
        #undef MINMAX_CHANGED
        #define SOMTGD_MINMAX_CHANGED 1
    #else
        #define MINMAX_CHANGED WPDCF77_MINMAX_CHANGED
    #endif /* MINMAX_CHANGED */
#endif /* SOMTGD_MINMAX_CHANGED */
#ifndef SOMTGD_MINMAX_WAIT4SIZE
    #ifdef MINMAX_WAIT4SIZE
        #undef MINMAX_WAIT4SIZE
        #define SOMTGD_MINMAX_WAIT4SIZE 1
    #else
        #define MINMAX_WAIT4SIZE WPDCF77_MINMAX_WAIT4SIZE
    #endif /* MINMAX_WAIT4SIZE */
#endif /* SOMTGD_MINMAX_WAIT4SIZE */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of bindings for IDL types.
 */

/*
 * Passthru lines: File: "C.h", "after"
 */



#define WPDCF77_MajorVersion 1
#define WPDCF77_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPDCF77NewClass wpDCF77c
#pragma linkage(wpDCF77c, system)
#define WPDCF77ClassData wpDCF77d
#define WPDCF77CClassData wpDCF77x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define WPDCF77_classObj WPDCF77ClassData.classObject
#define _WPDCF77 WPDCF77_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPDCF77NewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPDCF77NewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPDCF77ClassDataStructure {
	SOMClass *classObject;
	somMToken wpAddClockAlarmPage;
	somMToken wpAddClockAlarm2Page;
	somMToken wpAddClockAlarm3Page;
	somMToken wpAddClockDateTimePage;
	somMToken wpAddClockView1Page;
	somMToken wpAddClockView2Page;
	somMToken wpAddClockView3Page;
	somMToken wpAddDCFSettingPage1;
	somMToken wpAddDCFSettingPage2;
	somMToken wpAddDCFSettingPage3;
	somMToken wpAdd1sTimer;
	somMToken wpRemove1sTimer;
	somMToken wpCloseADView;
	somMToken wpAddTmOffsSettingPage;
	somMToken wpAddTZSettingPage;
	somMToken wpAddServerIntervalPage;
	somMToken wpRefreshClockView;
	somMToken wpAddAudioSetupPage;
} SOMDLINK WPDCF77ClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPDCF77CClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPDCF77CClassData;

/*
 * New and Renew macros for WPDCF77
 */
#define WPDCF77New() \
   ( _WPDCF77 ? \
	_somNew(_WPDCF77) \
	: ( WPDCF77NewClass(\
		WPDCF77_MajorVersion, \
		WPDCF77_MinorVersion),\
	   _somNew(_WPDCF77)))
#define WPDCF77Renew(buf) \
   ( _WPDCF77 ? \
	_somRenew(_WPDCF77, buf) \
	: ( WPDCF77NewClass(\
		WPDCF77_MajorVersion, \
		WPDCF77_MinorVersion),\
	   _somRenew(_WPDCF77, buf)))

/*
 * Override method: wpAddClockAlarmPage
 */
#define WPDCF77_wpAddClockAlarmPage(somSelf,hwndNotebook) \
	WPClock_wpAddClockAlarmPage(somSelf,hwndNotebook)

/*
 * Override method: wpAddClockDateTimePage
 */
#define WPDCF77_wpAddClockDateTimePage(somSelf,hwndNotebook) \
	WPClock_wpAddClockDateTimePage(somSelf,hwndNotebook)

/*
 * Override method: wpAddClockView1Page
 */
#define WPDCF77_wpAddClockView1Page(somSelf,hwndNotebook) \
	WPClock_wpAddClockView1Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddClockView2Page
 */
#define WPDCF77_wpAddClockView2Page(somSelf,hwndNotebook) \
	WPClock_wpAddClockView2Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddSettingsPages
 */
#define WPDCF77_wpAddSettingsPages(somSelf,hwndNotebook) \
	WPObject_wpAddSettingsPages(somSelf,hwndNotebook)

/*
 * Override method: wpInitData
 */
#define WPDCF77_wpInitData(somSelf) \
	WPObject_wpInitData(somSelf)

/*
 * Override method: wpUnInitData
 */
#define WPDCF77_wpUnInitData(somSelf) \
	WPObject_wpUnInitData(somSelf)

/*
 * Override method: wpModifyPopupMenu
 */
#define WPDCF77_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition) \
	WPObject_wpModifyPopupMenu(somSelf,hwndMenu,hwndCnr,iPosition)

/*
 * Override method: wpFilterPopupMenu
 */
#define WPDCF77_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect) \
	WPObject_wpFilterPopupMenu(somSelf,ulFlags,hwndCnr,fMultiSelect)

/*
 * Override method: wpMenuItemSelected
 */
#define WPDCF77_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpOpen
 */
#define WPDCF77_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * Override method: wpRestoreState
 */
#define WPDCF77_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpSaveState
 */
#define WPDCF77_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpQueryDefaultView
 */
#define WPDCF77_wpQueryDefaultView(somSelf) \
	WPObject_wpQueryDefaultView(somSelf)

/*
 * New Method: wpAddClockAlarm2Page
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddClockAlarm2Page(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddClockAlarm2Page, system)
typedef somTP_WPDCF77_wpAddClockAlarm2Page *somTD_WPDCF77_wpAddClockAlarm2Page;
#define somMD_WPDCF77_wpAddClockAlarm2Page "::WPDCF77::wpAddClockAlarm2Page"
#define WPDCF77_wpAddClockAlarm2Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddClockAlarm2Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddClockAlarm2Page
    #if (defined(_wpAddClockAlarm2Page) || defined(__wpAddClockAlarm2Page))
        #undef _wpAddClockAlarm2Page
        #undef __wpAddClockAlarm2Page
        #define SOMGD_wpAddClockAlarm2Page 1
    #else
        #define _wpAddClockAlarm2Page WPDCF77_wpAddClockAlarm2Page
    #endif /* _wpAddClockAlarm2Page */
#endif /* SOMGD_wpAddClockAlarm2Page */

/*
 * New Method: wpAddClockAlarm3Page
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddClockAlarm3Page(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddClockAlarm3Page, system)
typedef somTP_WPDCF77_wpAddClockAlarm3Page *somTD_WPDCF77_wpAddClockAlarm3Page;
#define somMD_WPDCF77_wpAddClockAlarm3Page "::WPDCF77::wpAddClockAlarm3Page"
#define WPDCF77_wpAddClockAlarm3Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddClockAlarm3Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddClockAlarm3Page
    #if (defined(_wpAddClockAlarm3Page) || defined(__wpAddClockAlarm3Page))
        #undef _wpAddClockAlarm3Page
        #undef __wpAddClockAlarm3Page
        #define SOMGD_wpAddClockAlarm3Page 1
    #else
        #define _wpAddClockAlarm3Page WPDCF77_wpAddClockAlarm3Page
    #endif /* _wpAddClockAlarm3Page */
#endif /* SOMGD_wpAddClockAlarm3Page */

/*
 * New Method: wpAddClockView3Page
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddClockView3Page(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddClockView3Page, system)
typedef somTP_WPDCF77_wpAddClockView3Page *somTD_WPDCF77_wpAddClockView3Page;
#define somMD_WPDCF77_wpAddClockView3Page "::WPDCF77::wpAddClockView3Page"
#define WPDCF77_wpAddClockView3Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddClockView3Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddClockView3Page
    #if (defined(_wpAddClockView3Page) || defined(__wpAddClockView3Page))
        #undef _wpAddClockView3Page
        #undef __wpAddClockView3Page
        #define SOMGD_wpAddClockView3Page 1
    #else
        #define _wpAddClockView3Page WPDCF77_wpAddClockView3Page
    #endif /* _wpAddClockView3Page */
#endif /* SOMGD_wpAddClockView3Page */

/*
 * New Method: wpAddDCFSettingPage1
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddDCFSettingPage1(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddDCFSettingPage1, system)
typedef somTP_WPDCF77_wpAddDCFSettingPage1 *somTD_WPDCF77_wpAddDCFSettingPage1;
#define somMD_WPDCF77_wpAddDCFSettingPage1 "::WPDCF77::wpAddDCFSettingPage1"
#define WPDCF77_wpAddDCFSettingPage1(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddDCFSettingPage1) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddDCFSettingPage1
    #if (defined(_wpAddDCFSettingPage1) || defined(__wpAddDCFSettingPage1))
        #undef _wpAddDCFSettingPage1
        #undef __wpAddDCFSettingPage1
        #define SOMGD_wpAddDCFSettingPage1 1
    #else
        #define _wpAddDCFSettingPage1 WPDCF77_wpAddDCFSettingPage1
    #endif /* _wpAddDCFSettingPage1 */
#endif /* SOMGD_wpAddDCFSettingPage1 */

/*
 * New Method: wpAddDCFSettingPage2
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddDCFSettingPage2(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddDCFSettingPage2, system)
typedef somTP_WPDCF77_wpAddDCFSettingPage2 *somTD_WPDCF77_wpAddDCFSettingPage2;
#define somMD_WPDCF77_wpAddDCFSettingPage2 "::WPDCF77::wpAddDCFSettingPage2"
#define WPDCF77_wpAddDCFSettingPage2(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddDCFSettingPage2) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddDCFSettingPage2
    #if (defined(_wpAddDCFSettingPage2) || defined(__wpAddDCFSettingPage2))
        #undef _wpAddDCFSettingPage2
        #undef __wpAddDCFSettingPage2
        #define SOMGD_wpAddDCFSettingPage2 1
    #else
        #define _wpAddDCFSettingPage2 WPDCF77_wpAddDCFSettingPage2
    #endif /* _wpAddDCFSettingPage2 */
#endif /* SOMGD_wpAddDCFSettingPage2 */

/*
 * New Method: wpAddDCFSettingPage3
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddDCFSettingPage3(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddDCFSettingPage3, system)
typedef somTP_WPDCF77_wpAddDCFSettingPage3 *somTD_WPDCF77_wpAddDCFSettingPage3;
#define somMD_WPDCF77_wpAddDCFSettingPage3 "::WPDCF77::wpAddDCFSettingPage3"
#define WPDCF77_wpAddDCFSettingPage3(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddDCFSettingPage3) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddDCFSettingPage3
    #if (defined(_wpAddDCFSettingPage3) || defined(__wpAddDCFSettingPage3))
        #undef _wpAddDCFSettingPage3
        #undef __wpAddDCFSettingPage3
        #define SOMGD_wpAddDCFSettingPage3 1
    #else
        #define _wpAddDCFSettingPage3 WPDCF77_wpAddDCFSettingPage3
    #endif /* _wpAddDCFSettingPage3 */
#endif /* SOMGD_wpAddDCFSettingPage3 */

/*
 * New Method: wpAddTmOffsSettingPage
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddTmOffsSettingPage(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddTmOffsSettingPage, system)
typedef somTP_WPDCF77_wpAddTmOffsSettingPage *somTD_WPDCF77_wpAddTmOffsSettingPage;
#define somMD_WPDCF77_wpAddTmOffsSettingPage "::WPDCF77::wpAddTmOffsSettingPage"
#define WPDCF77_wpAddTmOffsSettingPage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddTmOffsSettingPage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddTmOffsSettingPage
    #if (defined(_wpAddTmOffsSettingPage) || defined(__wpAddTmOffsSettingPage))
        #undef _wpAddTmOffsSettingPage
        #undef __wpAddTmOffsSettingPage
        #define SOMGD_wpAddTmOffsSettingPage 1
    #else
        #define _wpAddTmOffsSettingPage WPDCF77_wpAddTmOffsSettingPage
    #endif /* _wpAddTmOffsSettingPage */
#endif /* SOMGD_wpAddTmOffsSettingPage */

/*
 * New Method: wpAddTZSettingPage
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddTZSettingPage(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddTZSettingPage, system)
typedef somTP_WPDCF77_wpAddTZSettingPage *somTD_WPDCF77_wpAddTZSettingPage;
#define somMD_WPDCF77_wpAddTZSettingPage "::WPDCF77::wpAddTZSettingPage"
#define WPDCF77_wpAddTZSettingPage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddTZSettingPage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddTZSettingPage
    #if (defined(_wpAddTZSettingPage) || defined(__wpAddTZSettingPage))
        #undef _wpAddTZSettingPage
        #undef __wpAddTZSettingPage
        #define SOMGD_wpAddTZSettingPage 1
    #else
        #define _wpAddTZSettingPage WPDCF77_wpAddTZSettingPage
    #endif /* _wpAddTZSettingPage */
#endif /* SOMGD_wpAddTZSettingPage */

/*
 * New Method: wpAddServerIntervalPage
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddServerIntervalPage(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddServerIntervalPage, system)
typedef somTP_WPDCF77_wpAddServerIntervalPage *somTD_WPDCF77_wpAddServerIntervalPage;
#define somMD_WPDCF77_wpAddServerIntervalPage "::WPDCF77::wpAddServerIntervalPage"
#define WPDCF77_wpAddServerIntervalPage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddServerIntervalPage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddServerIntervalPage
    #if (defined(_wpAddServerIntervalPage) || defined(__wpAddServerIntervalPage))
        #undef _wpAddServerIntervalPage
        #undef __wpAddServerIntervalPage
        #define SOMGD_wpAddServerIntervalPage 1
    #else
        #define _wpAddServerIntervalPage WPDCF77_wpAddServerIntervalPage
    #endif /* _wpAddServerIntervalPage */
#endif /* SOMGD_wpAddServerIntervalPage */

/*
 * New Method: wpAddAudioSetupPage
 */
typedef ULONG   SOMLINK somTP_WPDCF77_wpAddAudioSetupPage(WPDCF77 *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPDCF77_wpAddAudioSetupPage, system)
typedef somTP_WPDCF77_wpAddAudioSetupPage *somTD_WPDCF77_wpAddAudioSetupPage;
#define somMD_WPDCF77_wpAddAudioSetupPage "::WPDCF77::wpAddAudioSetupPage"
#define WPDCF77_wpAddAudioSetupPage(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPDCF77, wpAddAudioSetupPage) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpAddAudioSetupPage
    #if (defined(_wpAddAudioSetupPage) || defined(__wpAddAudioSetupPage))
        #undef _wpAddAudioSetupPage
        #undef __wpAddAudioSetupPage
        #define SOMGD_wpAddAudioSetupPage 1
    #else
        #define _wpAddAudioSetupPage WPDCF77_wpAddAudioSetupPage
    #endif /* _wpAddAudioSetupPage */
#endif /* SOMGD_wpAddAudioSetupPage */

/*
 * New Method: wpAdd1sTimer
 */
typedef BOOL   SOMLINK somTP_WPDCF77_wpAdd1sTimer(WPDCF77 *somSelf, 
		HWND hwndReceiver);
#pragma linkage(somTP_WPDCF77_wpAdd1sTimer, system)
typedef somTP_WPDCF77_wpAdd1sTimer *somTD_WPDCF77_wpAdd1sTimer;
#define somMD_WPDCF77_wpAdd1sTimer "::WPDCF77::wpAdd1sTimer"
#define WPDCF77_wpAdd1sTimer(somSelf,hwndReceiver) \
    (SOM_Resolve(somSelf, WPDCF77, wpAdd1sTimer) \
	(somSelf,hwndReceiver))
#ifndef SOMGD_wpAdd1sTimer
    #if (defined(_wpAdd1sTimer) || defined(__wpAdd1sTimer))
        #undef _wpAdd1sTimer
        #undef __wpAdd1sTimer
        #define SOMGD_wpAdd1sTimer 1
    #else
        #define _wpAdd1sTimer WPDCF77_wpAdd1sTimer
    #endif /* _wpAdd1sTimer */
#endif /* SOMGD_wpAdd1sTimer */

/*
 * New Method: wpRemove1sTimer
 */
typedef BOOL   SOMLINK somTP_WPDCF77_wpRemove1sTimer(WPDCF77 *somSelf, 
		HWND hwndReceiver);
#pragma linkage(somTP_WPDCF77_wpRemove1sTimer, system)
typedef somTP_WPDCF77_wpRemove1sTimer *somTD_WPDCF77_wpRemove1sTimer;
#define somMD_WPDCF77_wpRemove1sTimer "::WPDCF77::wpRemove1sTimer"
#define WPDCF77_wpRemove1sTimer(somSelf,hwndReceiver) \
    (SOM_Resolve(somSelf, WPDCF77, wpRemove1sTimer) \
	(somSelf,hwndReceiver))
#ifndef SOMGD_wpRemove1sTimer
    #if (defined(_wpRemove1sTimer) || defined(__wpRemove1sTimer))
        #undef _wpRemove1sTimer
        #undef __wpRemove1sTimer
        #define SOMGD_wpRemove1sTimer 1
    #else
        #define _wpRemove1sTimer WPDCF77_wpRemove1sTimer
    #endif /* _wpRemove1sTimer */
#endif /* SOMGD_wpRemove1sTimer */

/*
 * New Method: wpRefreshClockView
 */
typedef void   SOMLINK somTP_WPDCF77_wpRefreshClockView(WPDCF77 *somSelf);
#pragma linkage(somTP_WPDCF77_wpRefreshClockView, system)
typedef somTP_WPDCF77_wpRefreshClockView *somTD_WPDCF77_wpRefreshClockView;
#define somMD_WPDCF77_wpRefreshClockView "::WPDCF77::wpRefreshClockView"
#define WPDCF77_wpRefreshClockView(somSelf) \
    (SOM_Resolve(somSelf, WPDCF77, wpRefreshClockView) \
	(somSelf))
#ifndef SOMGD_wpRefreshClockView
    #if (defined(_wpRefreshClockView) || defined(__wpRefreshClockView))
        #undef _wpRefreshClockView
        #undef __wpRefreshClockView
        #define SOMGD_wpRefreshClockView 1
    #else
        #define _wpRefreshClockView WPDCF77_wpRefreshClockView
    #endif /* _wpRefreshClockView */
#endif /* SOMGD_wpRefreshClockView */

/*
 * New Method: wpCloseADView
 */
typedef void   SOMLINK somTP_WPDCF77_wpCloseADView(WPDCF77 *somSelf);
#pragma linkage(somTP_WPDCF77_wpCloseADView, system)
typedef somTP_WPDCF77_wpCloseADView *somTD_WPDCF77_wpCloseADView;
#define somMD_WPDCF77_wpCloseADView "::WPDCF77::wpCloseADView"
#define WPDCF77_wpCloseADView(somSelf) \
    (SOM_Resolve(somSelf, WPDCF77, wpCloseADView) \
	(somSelf))
#ifndef SOMGD_wpCloseADView
    #if (defined(_wpCloseADView) || defined(__wpCloseADView))
        #undef _wpCloseADView
        #undef __wpCloseADView
        #define SOMGD_wpCloseADView 1
    #else
        #define _wpCloseADView WPDCF77_wpCloseADView
    #endif /* _wpCloseADView */
#endif /* SOMGD_wpCloseADView */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPDCF77_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define WPDCF77_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPDCF77_wpFilterMenu WPObject_wpFilterMenu
#define WPDCF77_wpModifyMenu WPObject_wpModifyMenu
#define WPDCF77_somDefaultInit SOMObject_somDefaultInit
#define WPDCF77_somDestruct SOMObject_somDestruct
#define WPDCF77_wpQueryHandle WPObject_wpQueryHandle
#define WPDCF77_wpSaveImmediate WPObject_wpSaveImmediate
#define WPDCF77_wpSetTitle WPObject_wpSetTitle
#define WPDCF77_wpCopyObject WPObject_wpCopyObject
#define WPDCF77_wpMoveObject WPObject_wpMoveObject
#define WPDCF77_wpQueryIcon WPObject_wpQueryIcon
#define WPDCF77_wpQueryIconData WPObject_wpQueryIconData
#define WPDCF77_wpSetIconData WPObject_wpSetIconData
#define WPDCF77_wpDragOver WPObject_wpDragOver
#define WPDCF77_wpReplaceObject WPObject_wpReplaceObject
#define WPDCF77_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPDCF77_wpIdentify WPObject_wpIdentify
#define WPDCF77_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPDCF77_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPDCF77_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPDCF77_wpAllocMem WPObject_wpAllocMem
#define WPDCF77_wpAppendObject WPObject_wpAppendObject
#define WPDCF77_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPDCF77_wpClose WPObject_wpClose
#define WPDCF77_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPDCF77_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPDCF77_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPDCF77_wpConfirmDelete WPObject_wpConfirmDelete
#define WPDCF77_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPDCF77_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPDCF77_wpCreateAnother WPObject_wpCreateAnother
#define WPDCF77_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPDCF77_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPDCF77_wpDelete WPObject_wpDelete
#define WPDCF77_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPDCF77_wpDisplayHelp WPObject_wpDisplayHelp
#define WPDCF77_wpDisplayMenu WPObject_wpDisplayMenu
#define WPDCF77_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPDCF77_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPDCF77_wpDrop WPObject_wpDrop
#define WPDCF77_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPDCF77_wpEndConversation WPObject_wpEndConversation
#define WPDCF77_wpFindUseItem WPObject_wpFindUseItem
#define WPDCF77_wpFormatDragItem WPObject_wpFormatDragItem
#define WPDCF77_wpFree WPObject_wpFree
#define WPDCF77_wpFreeMem WPObject_wpFreeMem
#define WPDCF77_wpHide WPObject_wpHide
#define WPDCF77_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPDCF77_wpInsertMenuItems WPObject_wpInsertMenuItems
#define WPDCF77_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPDCF77_wpPrintObject WPObject_wpPrintObject
#define WPDCF77_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPDCF77_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPDCF77_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPDCF77_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPDCF77_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPDCF77_wpQueryError WPObject_wpQueryError
#define WPDCF77_wpSetFolder WPObject_wpSetFolder
#define WPDCF77_wpQueryFolder WPObject_wpQueryFolder
#define WPDCF77_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPDCF77_wpQueryStyle WPObject_wpQueryStyle
#define WPDCF77_wpSetTaskRec WPObject_wpSetTaskRec
#define WPDCF77_wpFindTaskRec WPObject_wpFindTaskRec
#define WPDCF77_wpQueryTitle WPObject_wpQueryTitle
#define WPDCF77_wpRegisterView WPObject_wpRegisterView
#define WPDCF77_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPDCF77_wpRender WPObject_wpRender
#define WPDCF77_wpRenderComplete WPObject_wpRenderComplete
#define WPDCF77_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPDCF77_wpRestore WPObject_wpRestore
#define WPDCF77_wpRestoreData WPObject_wpRestoreData
#define WPDCF77_wpRestoreLong WPObject_wpRestoreLong
#define WPDCF77_wpRestoreString WPObject_wpRestoreString
#define WPDCF77_wpSaveData WPObject_wpSaveData
#define WPDCF77_wpSaveDeferred WPObject_wpSaveDeferred
#define WPDCF77_wpSaveLong WPObject_wpSaveLong
#define WPDCF77_wpSaveString WPObject_wpSaveString
#define WPDCF77_wpScanSetupString WPObject_wpScanSetupString
#define WPDCF77_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPDCF77_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPDCF77_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPDCF77_wpSetDefaultView WPObject_wpSetDefaultView
#define WPDCF77_wpSetError WPObject_wpSetError
#define WPDCF77_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPDCF77_wpSetupOnce WPObject_wpSetupOnce
#define WPDCF77_wpSetIcon WPObject_wpSetIcon
#define WPDCF77_wpSetMinWindow WPObject_wpSetMinWindow
#define WPDCF77_wpModifyStyle WPObject_wpModifyStyle
#define WPDCF77_wpSetup WPObject_wpSetup
#define WPDCF77_wpSwitchTo WPObject_wpSwitchTo
#define WPDCF77_wpViewObject WPObject_wpViewObject
#define WPDCF77_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPDCF77_wpUnlockObject WPObject_wpUnlockObject
#define WPDCF77_wpObjectReady WPObject_wpObjectReady
#define WPDCF77_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPDCF77_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPDCF77_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPDCF77_wpIsDeleteable WPObject_wpIsDeleteable
#define WPDCF77_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPDCF77_wpSetObjectID WPObject_wpSetObjectID
#define WPDCF77_wpQueryObjectID WPObject_wpQueryObjectID
#define WPDCF77_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPDCF77_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPDCF77_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPDCF77_wpFindViewItem WPObject_wpFindViewItem
#define WPDCF77_wpLockObject WPObject_wpLockObject
#define WPDCF77_wpIsLocked WPObject_wpIsLocked
#define WPDCF77_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPDCF77_wpWaitForClose WPObject_wpWaitForClose
#define WPDCF77_wpSetMenuStyle WPObject_wpSetMenuStyle
#define WPDCF77_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define WPDCF77_wpSetStyle WPObject_wpSetStyle
#define WPDCF77_somInit SOMObject_somInit
#define WPDCF77_somUninit SOMObject_somUninit
#define WPDCF77_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPDCF77_somDefaultAssign SOMObject_somDefaultAssign
#define WPDCF77_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPDCF77_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPDCF77_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPDCF77_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPDCF77_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPDCF77_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPDCF77_somFree SOMObject_somFree
#define WPDCF77_somGetClass SOMObject_somGetClass
#define WPDCF77_somGetClassName SOMObject_somGetClassName
#define WPDCF77_somGetSize SOMObject_somGetSize
#define WPDCF77_somIsA SOMObject_somIsA
#define WPDCF77_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPDCF77_somRespondsTo SOMObject_somRespondsTo
#define WPDCF77_somDispatch SOMObject_somDispatch
#define WPDCF77_somClassDispatch SOMObject_somClassDispatch
#define WPDCF77_somCastObj SOMObject_somCastObj
#define WPDCF77_somResetObj SOMObject_somResetObj
#define WPDCF77_somDispatchV SOMObject_somDispatchV
#define WPDCF77_somDispatchL SOMObject_somDispatchL
#define WPDCF77_somDispatchA SOMObject_somDispatchA
#define WPDCF77_somDispatchD SOMObject_somDispatchD
#define WPDCF77_somPrintSelf SOMObject_somPrintSelf
#define WPDCF77_somDumpSelf SOMObject_somDumpSelf
#define WPDCF77_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPDCF77_h */

#ifndef SOM_M_WPDCF77_h
#define SOM_M_WPDCF77_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPDCF77
#define M_WPDCF77 SOMObject
#endif
#include <wpclock.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_WPDCF77_MajorVersion 1
#define M_WPDCF77_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPDCF77NewClass c
#pragma linkage(c, system)
#define M_WPDCF77ClassData d
#define M_WPDCF77CClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPDCF77_classObj M_WPDCF77ClassData.classObject
#define _M_WPDCF77 M_WPDCF77_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPDCF77NewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_WPDCF77NewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPDCF77ClassDataStructure {
	SOMClass *classObject;
	somMToken clsQueryModuleHandle;
	somMToken clsSaveSetData;
} SOMDLINK M_WPDCF77ClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPDCF77CClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPDCF77CClassData;

/*
 * New and Renew macros for M_WPDCF77
 */
#define M_WPDCF77New() \
   ( _M_WPDCF77 ? \
	_somNew(_M_WPDCF77) \
	: ( M_WPDCF77NewClass(\
		M_WPDCF77_MajorVersion, \
		M_WPDCF77_MinorVersion),\
	   _somNew(_M_WPDCF77)))
#define M_WPDCF77Renew(buf) \
   ( _M_WPDCF77 ? \
	_somRenew(_M_WPDCF77, buf) \
	: ( M_WPDCF77NewClass(\
		M_WPDCF77_MajorVersion, \
		M_WPDCF77_MinorVersion),\
	   _somRenew(_M_WPDCF77, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_WPDCF77_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsQueryIconData
 */
#define M_WPDCF77_wpclsQueryIconData(somSelf,pIconInfo) \
	M_WPObject_wpclsQueryIconData(somSelf,pIconInfo)

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPDCF77_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQueryDefaultHelp
 */
#define M_WPDCF77_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary) \
	M_WPObject_wpclsQueryDefaultHelp(somSelf,pHelpPanelId,pszHelpLibrary)

/*
 * New Method: clsQueryModuleHandle
 */
typedef HMODULE   SOMLINK somTP_M_WPDCF77_clsQueryModuleHandle(M_WPDCF77 *somSelf);
#pragma linkage(somTP_M_WPDCF77_clsQueryModuleHandle, system)
typedef somTP_M_WPDCF77_clsQueryModuleHandle *somTD_M_WPDCF77_clsQueryModuleHandle;
#define somMD_M_WPDCF77_clsQueryModuleHandle "::M_WPDCF77::clsQueryModuleHandle"
#define M_WPDCF77_clsQueryModuleHandle(somSelf) \
    (SOM_Resolve(somSelf, M_WPDCF77, clsQueryModuleHandle) \
	(somSelf))
#ifndef SOMGD_clsQueryModuleHandle
    #if (defined(_clsQueryModuleHandle) || defined(__clsQueryModuleHandle))
        #undef _clsQueryModuleHandle
        #undef __clsQueryModuleHandle
        #define SOMGD_clsQueryModuleHandle 1
    #else
        #define _clsQueryModuleHandle M_WPDCF77_clsQueryModuleHandle
    #endif /* _clsQueryModuleHandle */
#endif /* SOMGD_clsQueryModuleHandle */

/*
 * New Method: clsSaveSetData
 */
typedef void   SOMLINK somTP_M_WPDCF77_clsSaveSetData(M_WPDCF77 *somSelf, 
		ULONG flType);
#pragma linkage(somTP_M_WPDCF77_clsSaveSetData, system)
typedef somTP_M_WPDCF77_clsSaveSetData *somTD_M_WPDCF77_clsSaveSetData;
#define somMD_M_WPDCF77_clsSaveSetData "::M_WPDCF77::clsSaveSetData"
#define M_WPDCF77_clsSaveSetData(somSelf,flType) \
    (SOM_Resolve(somSelf, M_WPDCF77, clsSaveSetData) \
	(somSelf,flType))
#ifndef SOMGD_clsSaveSetData
    #if (defined(_clsSaveSetData) || defined(__clsSaveSetData))
        #undef _clsSaveSetData
        #undef __clsSaveSetData
        #define SOMGD_clsSaveSetData 1
    #else
        #define _clsSaveSetData M_WPDCF77_clsSaveSetData
    #endif /* _clsSaveSetData */
#endif /* SOMGD_clsSaveSetData */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPDCF77_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_WPDCF77_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_WPDCF77_wpclsQuerySetting M_WPAbstract_wpclsQuerySetting
#define M_WPDCF77_wpclsSetSetting M_WPAbstract_wpclsSetSetting
#define M_WPDCF77_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_WPDCF77_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_WPDCF77_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_WPDCF77_wpclsNew M_WPObject_wpclsNew
#define M_WPDCF77_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_WPDCF77_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_WPDCF77_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPDCF77_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_WPDCF77_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_WPDCF77_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPDCF77_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_WPDCF77_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_WPDCF77_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_WPDCF77_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_WPDCF77_wpclsSetError M_WPObject_wpclsSetError
#define M_WPDCF77_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPDCF77_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_WPDCF77_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_WPDCF77_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPDCF77_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPDCF77_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPDCF77_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPDCF77_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPDCF77_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPDCF77_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPDCF77_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPDCF77_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPDCF77_somUninit SOMObject_somUninit
#define M_WPDCF77_somClassReady SOMClass_somClassReady
#define M_WPDCF77_somNew SOMClass_somNew
#define M_WPDCF77_somRenew SOMClass_somRenew
#define M_WPDCF77__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPDCF77__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPDCF77__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPDCF77_somNewNoInit SOMClass_somNewNoInit
#define M_WPDCF77_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPDCF77_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPDCF77_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPDCF77_somAllocate SOMClass_somAllocate
#define M_WPDCF77_somDeallocate SOMClass_somDeallocate
#define M_WPDCF77_somInitClass SOMClass_somInitClass
#define M_WPDCF77_somInitMIClass SOMClass_somInitMIClass
#define M_WPDCF77_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPDCF77_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPDCF77_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPDCF77_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPDCF77_somGetClassData SOMClass_somGetClassData
#define M_WPDCF77_somSetClassData SOMClass_somSetClassData
#define M_WPDCF77_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPDCF77_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPDCF77_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPDCF77_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPDCF77_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPDCF77_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPDCF77_somGetMethodData SOMClass_somGetMethodData
#define M_WPDCF77_somGetRdStub SOMClass_somGetRdStub
#define M_WPDCF77_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPDCF77_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPDCF77_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPDCF77_somGetName SOMClass_somGetName
#define M_WPDCF77_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPDCF77_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPDCF77_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPDCF77_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPDCF77_somGetParent SOMClass_somGetParent
#define M_WPDCF77_somGetParents SOMClass_somGetParents
#define M_WPDCF77_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPDCF77_somFindMethod SOMClass_somFindMethod
#define M_WPDCF77_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPDCF77_somFindSMethod SOMClass_somFindSMethod
#define M_WPDCF77_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPDCF77_somLookupMethod SOMClass_somLookupMethod
#define M_WPDCF77_somCheckVersion SOMClass_somCheckVersion
#define M_WPDCF77_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPDCF77_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPDCF77_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPDCF77_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPDCF77_somDefaultInit SOMObject_somDefaultInit
#define M_WPDCF77_somDestruct SOMObject_somDestruct
#define M_WPDCF77_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPDCF77_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPDCF77_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPDCF77_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPDCF77_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPDCF77_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPDCF77_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPDCF77_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPDCF77_somInit SOMObject_somInit
#define M_WPDCF77_somFree SOMObject_somFree
#define M_WPDCF77_somGetClass SOMObject_somGetClass
#define M_WPDCF77_somGetClassName SOMObject_somGetClassName
#define M_WPDCF77_somGetSize SOMObject_somGetSize
#define M_WPDCF77_somIsA SOMObject_somIsA
#define M_WPDCF77_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPDCF77_somRespondsTo SOMObject_somRespondsTo
#define M_WPDCF77_somDispatch SOMObject_somDispatch
#define M_WPDCF77_somClassDispatch SOMObject_somClassDispatch
#define M_WPDCF77_somCastObj SOMObject_somCastObj
#define M_WPDCF77_somResetObj SOMObject_somResetObj
#define M_WPDCF77_somDispatchV SOMObject_somDispatchV
#define M_WPDCF77_somDispatchL SOMObject_somDispatchL
#define M_WPDCF77_somDispatchA SOMObject_somDispatchA
#define M_WPDCF77_somDispatchD SOMObject_somDispatchD
#define M_WPDCF77_somPrintSelf SOMObject_somPrintSelf
#define M_WPDCF77_somDumpSelf SOMObject_somDumpSelf
#define M_WPDCF77_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPDCF77_h */
