/* Fehlermeldungen */
#define ERROR_BREAK         "Programm kann zur Zeit nicht abgebrochen werden...\n"
#define ERROR_SERVER        "Server nicht erreichbar\n"
#define ERROR_CLIENT        "Client ist bereits aktiv!\n"
#define ERROR_ALLOC         "Server ist bereits aktiv!\n"
#define ERROR_NETBIOS       "Netbios kann nicht initialisiert werden!\n"
#define ERROR_THREAD        "Interner Fehler: Thread kann nicht erzeugt werden!\n"

#define TXT_VERSMAJOR       "Server Version, Major Code = %d\n"
#define TXT_VERSMINOR       "Server Version, Minor Code = %d\n"
#define TXT_VERCMAJOR       "Client Version, Major Code = %d\n"
#define TXT_VERCMINOR       "Client Version, Minor Code = %d\n"
#define TXT_VERSION         "Falsche Server-Version\n"
#define TXT_VALID           "gÅltige Zeit empfangen:               %.2d.%.2d.%4d / %.2d:%.2d:%.2d\n"
#define TXT_INVALID         "ungÅltige Zeit empfangen; Systemzeit: %.2d.%.2d.%4d / %.2d:%.2d:%.2d\n"
#define TXT_RECEIVE         "Receive thread erzeugt\n"
#define TXT_ENTERGET        "----------------------------------------\nenter getDataBlock...\n"
#define TXT_EXITGET         "...getDataBlock done\n"
#define TXT_SETDATETIME     "return from DosSetDateTime = %d\n"
#define TXT_WAIT            "now wait forever\n"

