/* Fehlermeldungen */
#define ERROR_BREAK         "Programm kann zur Zeit nicht abgebrochen werden...\n"
#define ERROR_SEMAPHORE     "Semaphore kann nicht erzeugt werden!\n"
#define ERROR_DRIVER        "Kein DCF77-Treiber gefunden!\n"
#define ERROR_ALLOC         "Server ist bereits aktiv!\n"
#define ERROR_CLIENT        "Client ist bereits aktiv!\n"
#define ERROR_NETBIOS       "Netbios kann nicht initialisiert werden!\n"
#define ERROR_WRITE         "Fehler beim Schreiben auf LAN\n"

#define TXT_VALID           "gÅltige Zeit empfangen:               %.2d.%.2d.%4d / %.2d:%.2d:%.2d"
#define TXT_INVALID         "ungÅltige Zeit empfangen; Systemzeit: %.2d.%.2d.%4d / %.2d:%.2d:%.2d"
#define TXT_BEGINSEND       " S "
#define TXT_ENDSENDOK       " OK"
#define TXT_ENDSENDERR      " ERR"

