NAME            SETADDR WINDOWAPI
STUB            'OS2STUB.EXE'
DESCRIPTION     '@#NB:X.XX.XX#@ Hopf 603x IO-Set Program'
CODE            LOADONCALL MOVEABLE
DATA            LOADONCALL MOVEABLE MULTIPLE READWRITE
HEAPSIZE        4096
STACKSIZE       16384
EXPORTS
