
.all: \
  .\hotspot.exe \

.SUFFIXES:

.SUFFIXES: .c

.c.obj:
      @echo " Compile::C++ Compiler "
      icc.exe /I. /Ss /Q /Wcnveffparprorearetuse /G5 /Fo"%|fF.obj" /Ms /C %s

.\hotspot.exe: \
    .\hotspot.obj \
    .\hotspot.def \
    MAKEFILE
      @echo "Link::Linker "
      icc.exe @<<
 /B"/pmtype:vio /nologo "
 /Fhotspot.exe
 hotspot.def
 .\hotspot.obj
<<

.\hotspot.obj: \
    .\hotspot.c \
    .\bitmap.h \
    MAKEFILE

cleanall:
      @if exist *.obj del *.obj
      @if exist *.exe del *.exe

