 SET PATH=D:\MSC;D:\MSC\BOUND;D:\MASM6\;D:\MASM6\BINP\;D:\MASM6\BINB\;%PATH%
 SET LIB=D:\LIB;D:\TOOLKIT\OS2LIB;D:\IBMCPP\LIB;
 SET INCLUDE=D:\MASM\INCLUDE\;D:\MSC\INCLUDE;D:\TOOLKT21\C\OS2H;D:\TOOLKT21\ASM\OS2INC;D:\IBMCPP\INCLUDE;D:\IBMCPP\IBMCLASS;
